# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
