# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='UserDetails',
        ),
    ]
